name = "ImplicitSVARCop"
uuid = "e0577d19-d843-412a-a5ef-0589e1b3514a"
version = "0.0.1"

[deps]
ARS = "5744327c-528e-406a-a16f-961c23f1e1d8"
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
AdvancedMH = "5b7e9947-ddc0-4b3f-9b55-0d8042f74170"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCChainsStorage = "51a256e2-afd8-4c38-88d8-a98ba8ad53ca"
MergeSorted = "5f6ebb72-d4a9-4954-9a69-49758639d560"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SliceSampling = "43f4d3e8-9711-4a8c-bd1b-03ac73a255cf"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[sources]
ARS = {rev = "main", url = "https://github.com/Eliassj/ARS.jl.git"}

[compat]
CSV = "0.10.15"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff"]
